grammar NTUFPI;
import NTUFPI_lexer;

noticia: paragrafo+ EOF;
paragrafo: frase+ '\n'*;
frase: (ARTIGO | PALAVRA | DIA_DA_SEMANA | MES | HORARIO | ADVERBIO | PORCENTAGEM | PONTUACAO | SIGLA | NOME_PROPRIO | DINHEIRO | ESTADO | NUMERO | DATA | ABREVIACAO | ABREVIACAO | PREPOSICAO | PRONOME | CIDADE | TEMPO | CONJUNCAO)* PONTO_FINAL;
Space: [ \t\r\n] -> skip;